### ISSUE TITLE
[BUG] Unsupported .version 7.6; current version is '7.5'

### ISSUE THREAD

**Issue by yuxiangl** [NVIDIA-Merlin/Merlin#289]
### Environment details:

Environment location: Docker

Method of NVTabular install: Docker

I tried the following images:
- nvcr.io/nvidia/merlin/merlin-pytorch-training:22.02
- nvcr.io/nvidia/merlin/merlin-pytorch-training:22.03
- nvcr.io/nvidia/merlin/merlin-pytorch-training:22.04

### Issue

I am trying to run the following example code from https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.DataFrame.rolling.html

```
import cudf
import pandas as pd
import numpy as np
a = cudf.Series(
    [1, 9, 5, 4, np.nan, 1],
    index=[
        pd.Timestamp('20190101 09:00:00'),
        pd.Timestamp('20190101 09:00:01'),
        pd.Timestamp('20190101 09:00:02'),
        pd.Timestamp('20190101 09:00:04'),
        pd.Timestamp('20190101 09:00:07'),
        pd.Timestamp('20190101 09:00:08')
    ]
)
print(a.rolling('2s').max())
```

But I got this error:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 2160, in add_ptx
    driver.cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    print(a.rolling('2s').max())
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/frame.py", line 4769, in rolling
    return Rolling(
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/window/rolling.py", line 179, in __init__
    self._normalize()
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/window/rolling.py", line 394, in _normalize
    self.window = self._window_to_window_sizes(window)
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/window/rolling.py", line 405, in _window_to_window_sizes
    return cudautils.window_sizes_from_offset(
  File "/opt/conda/lib/python3.8/site-packages/cudf/utils/cudautils.py", line 177, in window_sizes_from_offset
    gpu_window_sizes_from_offset.forall(arr.size)(
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 361, in __call__
    kernel = self.kernel.specialize(*args)
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 1021, in specialize
    specialization = Dispatcher(self.py_func, [types.void(*argtypes)],
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 899, in __init__
    self.compile(sigs[0])
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 1102, in compile
    kernel.bind()
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 590, in bind
    self._func.get()
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 441, in get
    linker.add_ptx(ptx)
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 2163, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.6; current version is '7.5'
```

This could be related to #159

**Comment by EvenOldridge** [comment]
Hi @yuxiangl, can you please post over on https://github.com/rapidsai/cudf

We use cudf as a core library but we don't support it within this team.
